### ISSUE TITLE
running hello_world example in windows: docker: Error response from daemon: invalid mode: \mlperf\mlbox_11062020\box_examples\hello_world\workspace/chats

### ISSUE THREAD

**Issue by hshaikusa** [mlperf/mlbox#140]
while running hello_world example in windows, getting the following errors:
**mlcommons versions installed:**
mlcommons-box             0.2.3
mlcommons-box-docker      0.2.3
mlcommons-box-singularity 0.2.3
mlcommons-box-ssh         0.2.3
mlspeclib                 1.0.0

docker run --rm  --net=host --privileged=true --volume C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/names:/mlbox_io0/C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/names --volume C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/chats:/mlbox_io1/C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/chats  mlperf/mlbox_hello_world:0.0.1 hello --name=/mlbox_io0/C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/names/alice.txt --chat=/mlbox_io1/C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/chats/chat_with_alice.txt
**docker: Error response from daemon: invalid mode: \mlperf\mlbox_11062020\box_examples\hello_world\workspace/chats.
**
See 'docker run --help'.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\mlbox_11062020\Scripts\mlcommons_box_docker.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\site-packages\mlcommons_box_docker\__main__.py", line 45, in run
    runner.run()
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\site-packages\mlcommons_box_docker\docker_run.py", line 72, in run
    self._run_or_die(cmd)
  File "c:\programdata\anaconda3\envs\mlbox_11062020\lib\site-packages\mlcommons_box_docker\docker_run.py", line 117, in _run_or_die
    raise RuntimeError('Command failed: {}'.format(cmd))
RuntimeError: Command failed: docker run --rm  --net=host --privileged=true --volume C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/names:/mlbox_io0/C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/names --volume C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/chats:/mlbox_io1/C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/chats  mlperf/mlbox_hello_world:0.0.1 hello --name=/mlbox_io0/C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/names/alice.txt --chat=/mlbox_io1/C:\mlperf\mlbox_11062020\box_examples\hello_world\workspace/chats/chat_with_alice.txt

**Comment by sub-mod** [comment]
to me it looks like Volume Mounts are not Working
